### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by simonwuelker** [Wuelle/rust_nn#1]
- [x] Add a working implementation for basic dual number operations (`Add`, `AddAssign` etc)
- [x] Allow interfacing with regular numbers implementing `num_traits::Float` 
- [ ] Use standard floating point types for weights/biases, these don't require gradients. 
see https://github.com/rust-ndarray/ndarray/issues/1067
- [ ] Implement SGD using Dual Numbers
- [ ] Test Performance + Memory usage. Dual Numbers might be really bad

**Comment by archuser555** [comment]
Can I Help? :-)

**Comment by simonwuelker** [comment]
Hey, I haven't really worked on this project for a while (and it's probably fair to consider it dead ^^ )
I did some rough calculations and my initial idea of using dual numbers for automatic differentiation would lead to a completely ridiculous amount of memory required. I really appreciate the though but if you want to build a NN library you're probably better of starting a new repo. I might pick this up again at some point but I don't have the time to work on this right now. You are welcome to fork this and do whatever with it.
